ModeloBundle\Entity\Tdepartamento:
    type: entity
    table: tdepartamento
    id:
        pkiddepartamento:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombredepartamento:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
