ModeloBundle\Entity\Thistorialjugadas:
    type: entity
    table: thistorialjugadas
    indexes:
        fkidempresa:
            columns:
                - fkidempresa
        fkiduduario:
            columns:
                - fkidusuario
    id:
        pkidhistorial:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fkidusuario:
            type: integer
            nullable: false
            options:
                unsigned: false
        fkidempresa:
            type: integer
            nullable: false
            options:
                unsigned: false
        premio:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        condicion:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        createdat:
            type: datetime
            nullable: false
        vence:
            type: datetime
            nullable: true
        tipo:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
        fkidcupon:
            type: bigint
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
